### ISSUE TITLE
Add a table view wrapper type

### ISSUE THREAD

**Issue by juliohm** [JuliaData/TableOperations.jl#8]
I found the `select` function useful for selecting columns, and I understand that it is lazy, just wrapping the original table. Could it be extended to support selecting indices of rows as well besides the columns?

If you feel that this could be useful, I can try submit a PR soon. Need some guidance on the best practices here with table types. I am still digesting the conventions.

**Comment by quinnj** [comment]
Discussed here: https://discourse.julialang.org/t/table-views/45834/4?u=quinnj
